package com.infinitio.aivoiceplatform.stt.dto.runtime;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents the result returned by the speech-to-text runtime.
 *
 * @author Infinitio Digital
 * @version 1.0.0
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SttTranscriptionResponse {

    /**
     * Unique identifier of the active call.
     */
    private String callId;

    /**
     * Transcribed text generated by the STT provider.
     */
    private String transcript;

    /**
     * Language associated with the transcription.
     */
    private String language;

    /**
     * Indicates whether this is the final transcription result.
     */
    private boolean finalTranscript;

    /**
     * Probability associated with the detected language.
     */
    private Double languageProbability;

    /**
     * Provider that generated the transcription.
     */
    private String provider;

    /**
     * Time taken by the STT operation in milliseconds.
     */
    private Long latencyMs;
}