package com.infinitio.aivoiceplatform.tts.streaming;

/**
 * Listener for receiving audio chunks produced by a streaming
 * Text-to-Speech provider.
 *
 * <p>
 * Implementations receive audio incrementally as it becomes
 * available from the TTS provider.
 * </p>
 *
 * @author Infinitio Digital
 * @version 1.0.0
 */
@FunctionalInterface
public interface TtsAudioStreamListener {

    /**
     * Handles an audio chunk generated by the TTS provider.
     *
     * @param audioBytes audio chunk bytes
     * @param contentType content type of the audio chunk
     */
    void onAudioChunk(byte[] audioBytes, String contentType);
}