package com.infinitio.aivoiceplatform.telephony.service.impl;

import com.infinitio.aivoiceplatform.call.entity.Call;
import com.infinitio.aivoiceplatform.call.repository.CallRepository;
import com.infinitio.aivoiceplatform.callsession.constant.CallSessionStatus;
import com.infinitio.aivoiceplatform.callsession.service.CallSessionUpdateService;
import com.infinitio.aivoiceplatform.telephony.dto.request.TransferCallRequestDto;
import com.infinitio.aivoiceplatform.telephony.provider.TelephonyProvider;
import com.infinitio.aivoiceplatform.telephony.provider.TelephonyProviderRegistry;
import com.infinitio.aivoiceplatform.telephony.service.TelephonyMediaSessionService;
import com.infinitio.aivoiceplatform.telephony.service.TelephonyTransferExecutionService;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Default provider-neutral call transfer execution service.
 *
 * <p>
 * This service prepares and persists the application-side transfer
 * request before delegating provider-specific execution to the
 * configured telephony provider.
 * </p>
 *
 * <p>
 * The transfer destination is generated by the application Flow
 * runtime. The active media session is then closed so that the
 * telephony provider can continue with the configured handoff flow.
 * </p>
 *
 * @author Infinitio Digital
 * @version 1.0.0
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class TelephonyTransferExecutionServiceImpl
        implements TelephonyTransferExecutionService {

    private final TelephonyProviderRegistry
            telephonyProviderRegistry;

    private final TelephonyMediaSessionService
            telephonyMediaSessionService;

    private final CallRepository
            callRepository;

    private final CallSessionUpdateService
            callSessionUpdateService;

    /**
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public void executeTransfer(
            String providerCode,
            TransferCallRequestDto request) {

        validateRequest(
                providerCode,
                request
        );

        log.info(
                "Preparing application-side call transfer. "
                        + "provider={}, providerCallId={}, "
                        + "destination={}",
                providerCode,
                request.getProviderCallId(),
                request.getDestination()
        );

        Call call =
                findCallByProviderCallId(
                        request.getProviderCallId()
                );

        /*
         * ---------------------------------------------------------
         * PERSIST APPLICATION TRANSFER STATE
         * ---------------------------------------------------------
         *
         * The application owns the transfer decision.
         *
         * This state must be persisted before the media session
         * is closed because the following telephony handoff step
         * may need to retrieve the destination from the database.
         */
        call.setTransferRequested(
                true
        );

        call.setTransferDestination(
                request.getDestination()
        );

        Call savedCall =
                callRepository.save(
                        call
                );

        log.info(
                "Application transfer state persisted. "
                        + "callId={}, providerCallId={}, "
                        + "destination={}",
                savedCall.getPublicId(),
                savedCall.getProviderCallId(),
                savedCall.getTransferDestination()
        );

        /*
         * ---------------------------------------------------------
         * UPDATE CALL SESSION STATE
         * ---------------------------------------------------------
         */
        updateCallSessionStatus(
                savedCall.getPublicId()
        );

        /*
         * ---------------------------------------------------------
         * CLOSE ACTIVE MEDIA SESSION
         * ---------------------------------------------------------
         *
         * Closing the active Exotel media stream allows Exotel
         * to continue with the next configured application step.
         */
        telephonyMediaSessionService.closeSession(
                providerCode,
                request.getProviderCallId(),
                "CALL_TRANSFER"
        );

        log.info(
                "Telephony media session close requested for transfer. "
                        + "provider={}, providerCallId={}",
                providerCode,
                request.getProviderCallId()
        );

        /*
         * ---------------------------------------------------------
         * PROVIDER-SPECIFIC EXECUTION
         * ---------------------------------------------------------
         */
        TelephonyProvider provider =
                telephonyProviderRegistry.getProvider(
                        providerCode
                );

        provider.transferCall(
                request
        );

        log.info(
                "Application-side transfer execution completed. "
                        + "provider={}, providerCallId={}, "
                        + "destination={}",
                providerCode,
                request.getProviderCallId(),
                request.getDestination()
        );
    }

    /**
     * Finds the application Call using the provider call identifier.
     *
     * @param providerCallId provider supplied call identifier
     * @return matching Call
     */
    private Call findCallByProviderCallId(
            String providerCallId) {

        return callRepository
                .findByProviderCallId(
                        providerCallId
                )
                .orElseThrow(() -> {

                    log.warn(
                            "Call not found for transfer. "
                                    + "providerCallId={}",
                            providerCallId
                    );

                    return new IllegalStateException(
                            "Call not found for provider call ID."
                    );
                });
    }

    /**
     * Updates the corresponding CallSession to TRANSFERRING.
     *
     * @param callId application call identifier
     */
    private void updateCallSessionStatus(
            String callId) {

        if (callId == null
                || callId.isBlank()) {

            log.warn(
                    "CallSession status cannot be updated because "
                            + "application call ID is missing."
            );

            return;
        }

        try {

            callSessionUpdateService.updateStatus(
                    callId,
                    CallSessionStatus.TRANSFERRING
            );

            log.info(
                    "CallSession marked as TRANSFERRING. "
                            + "callId={}",
                    callId
            );

        } catch (Exception exception) {

            log.warn(
                    "Unable to update CallSession status to "
                            + "TRANSFERRING. callId={}",
                    callId,
                    exception
            );
        }
    }

    /**
     * Validates the transfer execution request.
     *
     * @param providerCode telephony provider code
     * @param request transfer request
     */
    private void validateRequest(
            String providerCode,
            TransferCallRequestDto request) {

        if (providerCode == null
                || providerCode.isBlank()) {

            throw new IllegalArgumentException(
                    "Telephony provider code is required."
            );
        }

        if (request == null) {

            throw new IllegalArgumentException(
                    "Transfer request is required."
            );
        }

        if (request.getProviderCallId() == null
                || request.getProviderCallId().isBlank()) {

            throw new IllegalArgumentException(
                    "Provider call ID is required for transfer."
            );
        }

        if (request.getDestination() == null
                || request.getDestination().isBlank()) {

            throw new IllegalArgumentException(
                    "Transfer destination is required."
            );
        }
    }
}