package com.infinitio.aivoiceplatform.llm.dto.runtime;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents the runtime response generated by the configured LLM provider.
 *
 * <p>
 * This DTO is provider-independent and contains only information required
 * by the runtime and conversation-orchestration layers.
 * </p>
 *
 * @author Infinitio Digital
 * @version 1.0.0
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LlmGenerationResponseDto {

    /**
     * Unique identifier of the active call.
     */
    private String callId;

    /**
     * Generated assistant response.
     */
    private String content;

    /**
     * Language used for the response.
     */
    private String language;

    /**
     * Provider that generated the response.
     */
    private String provider;

    /**
     * Model used for generation.
     */
    private String model;

    /**
     * Indicates whether the generated response is final.
     */
    private boolean finalResponse;

    /**
     * Time taken to complete the provider request in milliseconds.
     */
    private Long latencyMs;

    /**
     * Number of input tokens consumed by the request.
     */
    private Long inputTokens;

    /**
     * Number of output tokens generated by the provider.
     */
    private Long outputTokens;

    /**
     * Total number of tokens consumed by the request.
     */
    private Long totalTokens;

    /**
     * Provider response identifier, when available.
     */
    private String providerRequestId;
}